server:
  port: 8999
spring:
  #服务名
  application:
    name: hotMap
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/day05
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.pangyu.hotmap.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#eurake的相关配置。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}

