server:
  port: 9999
spring:
  application:
    name: eruka_center_service
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9999/eureka/
