server:
  port: 8777
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
spring:
  application:
    name: service-product